
[settings]
activate_aggressive = false                    # Force mise tools to be first in PATH - causes issues with nix-shell if enabled
experimental = true                            # Enable Go backend for Mise
idiomatic_version_file_enable_tools = ["node"] # Use .nvmrc

[tools]
buf = "latest"
go = "1.25"
node = "24.12"
