
[settings]
activate_aggressive = true                     # Force mise tools to be first in PATH
experimental = true                            # Enable Go backend for Mise
idiomatic_version_file_enable_tools = ["node"] # Use .nvmrc

[tools]
buf = "latest"
go = "1.25"
node = "24.12"
